config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get '/home/about', to: 'homes#about', as: 'about'
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true, length: { in: 2..20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :is_matching_login_user, only: [:edit, :update, :destroy]

  def index
    @books = Book.all
    @side_bar = { user: current_user, form_value: Book.new }
    render layout: 'two_columns'
  end

  def create
    new_book = Book.new(book_params)
    new_book.user_id = current_user.id
    if new_book.save
      flash[:notice] = 'You have created book successfully.'
      redirect_to book_path(new_book.id)
    else
      @books = Book.all
      @side_bar = { user: current_user, form_value: new_book }
      render action: :index, layout: 'two_columns'
    end
  end

  def show
    @side_bar = { user: @book.user, form_value: Book.new }
    render layout: 'two_columns'
  end

  def edit
    @form_value = @book
  end

  def update
    if @book.update(book_params)
      flash[:notice] = 'You have updated book successfully.'
      redirect_to book_path(@book.id)
    else
      @form_value = @book
      render :edit
    end
  end

  def destroy
    @book.destroy
    flash[:notice] = 'You have destroyed book successfully.'
    redirect_to books_path
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def is_matching_login_user
    user = @book.user
    unless user.id == current_user.id
      redirect_to books_path
    end
  end

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update]
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @users = User.all
    @side_bar = { user: current_user, form_value: Book.new }
    render layout: 'two_columns'
  end

  def show
    @books = @user.books
    @side_bar = { user: @user, form_value: Book.new }
    render layout: 'two_columns'
  end

  def edit
    @form_value = @user
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'You have updated user successfully.'
      redirect_to user_path(@user.id)
    else
      @form_value = @user
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def is_matching_login_user
    unless @user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def to_alert_type(message_type)
    case message_type
    when "notice" then
      "alert-success"
    when "alert" then
      "alert-danger"
    end
  end

  def nav_links
    if user_signed_in? then
      [
        { path: user_path(current_user), method: :get, icon: 'fa-solid fa-house', text: 'Home'},
        { path: users_path, method: :get, icon: 'fa-solid fa-users', text: 'Users'},
        { path: books_path, method: :get, icon: 'fa-solid fa-book-open', text: 'Books'},
        { path: destroy_user_session_path, method: :delete, icon: 'fa-solid fa-right-from-bracket', text: 'Log out'},
      ]
    else
      [
        { path: root_path, method: :get, icon: 'fa-solid fa-house', text: 'Home'},
        { path: about_path, method: :get, icon: 'fa-solid fa-link', text: 'About'},
        { path: new_user_registration_path, method: :get, icon: 'fa-solid fa-user-plus', text: 'Sign up'},
        { path: new_user_session_path, method: :get, icon: 'fa-solid fa-right-to-bracket', text: 'Log in'},
      ]
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<section>
  <h2><%= form_title %></h2>
  <div class="card">
    <div class="card-body">
      <div class="form-body">
        <%= form_with model: form_value do |f| %>
          <%= render 'layouts/form_error', form_value: form_value %>
          <div class="form-group">
            <%= f.label :title, class: 'font-weight-bold' %>
            <%= f.text_field :title, placeholder: "本のタイトル", class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :body, class: 'font-weight-bold' %>
            <%= f.text_area :body, rows: "3", placeholder: "感想", class: "form-control" %>
          </div>
          <hr>
          <%= f.submit submit_text, class: "btn btn-block btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/books/_list.html.erb
<section>
  <h2>Books</h2>
  <table class="table">
    <thead class="font-weight-bold">
      <tr>
        <td class="align-middle"></td>
        <td class="align-middle">Title</td>
        <td class="align-middle">Opinion</td>
      </tr>
    </thead>
    <tbody>
      <% books.each do |book| %>
      <tr>
        <td class="align-middle">
          <%= link_to user_path(book.user) do %>
            <%= image_tag book.user.get_profile_image(80,80) %>
          <% end %>
        </td>
        <td class="align-middle"><%= link_to book.title, book_path(book.id) %></td>
        <td class="align-middle"><%= book.body %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/books/edit.html.erb
<div class="row">
  <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto">
    <%= render 'books/form', form_title: 'Editing Book', form_value: @form_value, submit_text: 'Update Book' %>
    <%= link_to 'Show', book_path(@book.id) %> | <%= link_to 'Back', books_path %>
  </div>
</div>

app/views/books/index.html.erb
<%= render 'books/list', books: @books %>

app/views/books/show.html.erb
<section>
  <h2>Book detail</h2>
  <div class="card">
    <div class="card-body">
      <h3 class="h4 card-title font-weight-bold"><%= @book.title %></h3>
      <p class="card-text"><%= @book.body %></p>
      <%= link_to user_path(@book.user.id), class: 'd-inline-flex' do %>
        <%= image_tag @book.user.get_profile_image(30,30) %>
        <span class="ml-1 align-middle"><%= @book.user.name %></span>
      <% end %>
    </div>
    <% if @book.user == current_user %>
    <div class="card-footer ">
      <%= link_to edit_book_path(@book.id), class: 'btn btn-success' do %>
        <i class="fa-solid fa-pen-to-square"></i><span>Edit</span>
      <% end %>
      <%= link_to book_path(@book.id), method: :delete, class: 'btn btn-danger' do %>
        <i class="fa-solid fa-trash-can"></i><span>Destroy</span>
      <% end %>
    </div>
    <% end %>
  </div>
</section>

app/views/homes/about.html.erb
<section class="jumbotron">
  <h1 class="display-4">About Bookers.</h1>
  <p class="lead">you can share and exchange your opinions, inpressions, and emotions about various books!</p>
</section>

app/views/homes/top.html.erb
<section class="jumbotron">
  <h1 class="display-4">Welcome to Bookers !!</h1>
  <p class="lead">In <i class="fa-solid fa-book"></i><strong>Bookers</strong>,</p>
  <p class="lead">you can share and exchange your opinions, inpressions, and emotions about various books!</p>
  <hr class="my-4">
  <%= link_to new_user_session_path, class: 'btn btn-info' do %>
    <i class="fa-solid fa-right-to-bracket"></i><span>Log in</span>
  <% end %>
  <%= link_to new_user_registration_path, class: 'btn btn-success' do %>
    <i class="fa-solid fa-user-plus"></i><span>Sign up</span>
  <% end %>
</section>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
<div class="row my-3">
  <div class="col">
    <div class="alert <%= to_alert_type(message_type) %>" role="alert"><%= message %></div>
  </div>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="d-flex justify-content-center">
  <p>CopyRight Infratop.inc</p>
</div>

app/views/layouts/_form_error.html.erb
<% if form_value.errors.any? %>
<div class="alert alert-danger" role="alert">
  <p class="alert-heading"><%= form_value.errors.count %> errors prohibited this obj from being saved:</p>
  <hr>
  <ul>
  <% form_value.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-sm">
  <div class="container">

    <%= link_to root_path, class: 'navbar-brand' do %>
      <i class="fa-solid fa-book"></i><span>Bookers</span>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
      <% nav_links.each do |nav_link| %>
        <li class="nav-item">
          <%= link_to nav_link[:path], method: nav_link[:method], class: 'nav-link' do %>
            <% if nav_link[:icon].present? %>
            <i class="<%= nav_link[:icon] %>"></i>
            <% end %>
            <span><%= nav_link[:text] %></span>
          <% end %>
        </li>
      <% end %>
      </ul>
    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/5afed4a8c8.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <%= render "layouts/header" %>
    </header>

    <div class="container">
      <%= render "layouts/flash" %>
      <div class="row my-3">
      <% if content_for?(:content) %>
        <%= yield(:content) %>
      <% else %>
        <main class="col">
          <%= yield %>
        </main>
      <% end %>
      </div>
    </div>

    <footer>
      <%= render "layouts/footer" %>
    </footer>
  </body>
</html>

app/views/layouts/two_columns.html.erb
<% content_for :content do %>
  <aside class="col-md-3">
    <%= render 'users/info', user: @side_bar[:user] %>
    <%= render 'books/form', form_title: 'New book', form_value: @side_bar[:form_value], submit_text: 'Create Book' %>
  </aside>
  <main class="col-md-8 offset-md-1">
    <%= yield %>
  </main>
<% end %>
<%= render template: 'layouts/application' %>

app/views/users/_form.html.erb
<section>
  <h2><%= form_title %></h2>
  <div class="card">
    <div class="card-body">
      <div class="form-body">
        <%= form_with model: form_value do |f| %>
          <%= render 'layouts/form_error', form_value: form_value %>
          <div class="form-group">
            <%= f.label :name, class: 'font-weight-bold' %>
            <%= f.text_field :name, placeholder: '名前', class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :profile_image, class: 'font-weight-bold' %>
            <%= f.file_field :profile_image, placeholder: 'プロフィール画像', accept: 'image/*', class: 'form-control-file' %>
          </div>
          <div class="form-group">
            <%= f.label :introduction, class: 'font-weight-bold' %>
            <%= f.text_area :introduction, rows: '3', placeholder: '自己紹介文', class: 'form-control' %>
          </div>
          <hr>
          <%= f.submit submit_text, class: 'btn btn-lg btn-block btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/_info.html.erb
<section class="mb-3">
  <h2>User info</h2>
  <div class="card">
    <div class="card-body">
      <%= image_tag user.get_profile_image(100,100), class: 'mb-3' %>
      <h3 class="h4 card-title font-weight-bold"><%= user.name %></h3>
      <p class="card-text"><%= user.introduction %></p>
    </div>
    <div class="card-footer">
      <%= link_to edit_user_path(user), class: 'btn btn-success btn-block' do %>
        <i class="fa-solid fa-user-gear"></i>
      <% end %>
    </div>
  </div>
</section>

app/views/users/_list.html.erb
<section>
  <h2>Users</h2>
  <table class="table">
    <thead class="font-weight-bold">
      <tr>
        <td class="align-middle">Image</td>
        <td class="align-middle">Name</td>
        <td class="align-middle"></td>
      </tr>
    </thead>
    <tbody>
      <% users.each do |user| %>
      <tr>
        <td class="align-middle">
          <%= image_tag user.get_profile_image(80,80) %>
        </td>
        <td class="align-middle"><%= user.name %></td>
        <td class="align-middle"><%= link_to 'Show', user_path(user.id) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto">
    <%= render 'users/form', form_title: 'User info', form_value: @form_value, submit_text: 'Update User' %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'users/list', users: @users %>

app/views/users/show.html.erb
<%= render 'books/list', books: @books %>